# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - eduquest-microservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5103be03006548c3a6fb27b42395ddfc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_43baa733b7ed4928ae13d3275334285f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5103be03006548c3a6fb27b42395ddfc }}/xeroxisxs/eduquest-microservice-flask:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'eduquest-microservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1667f40add954f16ac9ceb8b1957bdb7 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5103be03006548c3a6fb27b42395ddfc }}/xeroxisxs/eduquest-microservice-flask:${{ github.sha }}'