# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - EduQuest-Microservice-Flask

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f853a8b571584973896244535c5a4e1e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3d4ed796a3be47ffb76413ee50c36ee1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f853a8b571584973896244535c5a4e1e }}/zchua040/eduquest-microservice-flask:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EduQuest-Microservice-Flask'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5e74d668e0244bcea05c0ec8491e7e97 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f853a8b571584973896244535c5a4e1e }}/zchua040/eduquest-microservice-flask:${{ github.sha }}'